using System;

namespace SapODataClient.Model
{
    public class User
    {
        public Metadata __metadata { get; set; }
        public string userId { get; set; }
        public object salaryBudgetFinalSalaryPercentage { get; set; }
        public object dateOfCurrentPosition { get; set; }
        public object matrix1Label { get; set; }
        public object salary { get; set; }
        public string objective { get; set; }
        public object ssn { get; set; }
        public object state { get; set; }
        public object issueComments { get; set; }
        public string timeZone { get; set; }
        public string defaultLocale { get; set; }
        public object nationality { get; set; }
        public object salaryBudgetLumpsumPercentage { get; set; }
        public object sysCostOfSource { get; set; }
        public object ethnicity { get; set; }
        public string displayName { get; set; }
        public object payGrade { get; set; }
        public object nickname { get; set; }
        public object email { get; set; }
        public object salaryBudgetExtra2Percentage { get; set; }
        public object stockBudgetOther1Amount { get; set; }
        public object talentPool { get; set; }
        public object raiseProrating { get; set; }
        public object sysStartingSalary { get; set; }
        public object finalJobCode { get; set; }
        public object lumpsum2Target { get; set; }
        public object stockBudgetOptionAmount { get; set; }
        public object country { get; set; }
        public DateTime lastModifiedDateTime { get; set; }
        public object stockBudgetStockAmount { get; set; }
        public DateTime sciLastModified { get; set; }
        public object criticalTalentComments { get; set; }
        public object homePhone { get; set; }
        public object veteranSeparated { get; set; }
        public object stockBudgetOther2Amount { get; set; }
        public string firstName { get; set; }
        public object stockBudgetUnitAmount { get; set; }
        public object salutation { get; set; }
        public object impactOfLoss { get; set; }
        public object benchStrength { get; set; }
        public object sysSource { get; set; }
        public object futureLeader { get; set; }
        public string title { get; set; }
        public object meritEffectiveDate { get; set; }
        public object veteranProtected { get; set; }
        public object lumpsumTarget { get; set; }
        public object employeeClass { get; set; }
        public DateTime hireDate { get; set; }
        public object matrix2Label { get; set; }
        public object loginMethod { get; set; }
        public object salaryLocal { get; set; }
        public object citizenship { get; set; }
        public object reasonForLeaving { get; set; }
        public object riskOfLoss { get; set; }
        public string location { get; set; }
        public object reloComments { get; set; }
        public string username { get; set; }
        public object serviceDate { get; set; }
        public object reviewFreq { get; set; }
        public object salaryBudgetTotalRaisePercentage { get; set; }
        public object jobCode { get; set; }
        public DateTime lastModifiedWithTZ { get; set; }
        public string division { get; set; }
        public string custom02 { get; set; }
        public object meritTarget { get; set; }
        public string custom01 { get; set; }
        public object custom04 { get; set; }
        public object custom03 { get; set; }
        public object custom06 { get; set; }
        public string custom05 { get; set; }
        public object custom08 { get; set; }
        public object reloWilling { get; set; }
        public object custom07 { get; set; }
        public object stockBudgetOther3Amount { get; set; }
        public object custom09 { get; set; }
        public object onboardingId { get; set; }
        public object fax { get; set; }
        public object bonusBudgetAmount { get; set; }
        public object salaryBudgetPromotionPercentage { get; set; }
        public object dateOfPosition { get; set; }
        public object finalJobFamily { get; set; }
        public int teamMembersSize { get; set; }
        public object compensationEligible { get; set; }
        public object lastReviewDate { get; set; }
        public object compensationStockEligible { get; set; }
        public object businessPhone { get; set; }
        public string status { get; set; }
        public string lastName { get; set; }
        public object city { get; set; }
        public string competency { get; set; }
        public object businessSegment { get; set; }
        public object compensationSalaryRateUnits { get; set; }
        public object newToPosition { get; set; }
        public string assignmentUUID { get; set; }
        public DateTime dateOfBirth { get; set; }
        public object localCurrencyCode { get; set; }
        public object jobLevel { get; set; }
        public object custom11 { get; set; }
        public string defaultFullName { get; set; }
        public object custom10 { get; set; }
        public object compensationReadOnly { get; set; }
        public object custom13 { get; set; }
        public object custom12 { get; set; }
        public object custom15 { get; set; }
        public object custom14 { get; set; }
        public object veteranDisabled { get; set; }
        public string totalTeamSize { get; set; }
        public object married { get; set; }
        public string cellPhone { get; set; }
        public object veteranMedal { get; set; }
        public object compensationSalaryRateType { get; set; }
        public object zipCode { get; set; }
        public object jobTitle { get; set; }
        public object minority { get; set; }
        public object suffix { get; set; }
        public object matrixManaged { get; set; }
        public object bonusTarget { get; set; }
        public object addressLine1 { get; set; }
        public object jobFamily { get; set; }
        public object jobRole { get; set; }
        public object addressLine2 { get; set; }
        public object addressLine3 { get; set; }
        public object mi { get; set; }
        public string potential { get; set; }
        public object origHireDate { get; set; }
        public object level { get; set; }
        public object salaryBudgetMeritPercentage { get; set; }
        public object salaryProrating { get; set; }
        public DateTime lastModified { get; set; }
        public object promotionAmount { get; set; }
        public object impactOfLossComments { get; set; }
        public object empId { get; set; }
        public object compensationSalaryEligible { get; set; }
        public string department { get; set; }
        public bool isPrimaryAssignment { get; set; }
        public object reloLocation { get; set; }
        public object companyExitDate { get; set; }
        public object seatingChart { get; set; }
        public object finalJobRole { get; set; }
        public string performance { get; set; }
        public object compensationBonusEligible { get; set; }
        public object keyPosition { get; set; }
        public object salaryBudgetExtraPercentage { get; set; }
    }
}